spring:
  thymeleaf:
    encoding: UTF-8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Aprimons
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      smtp:
        mail:
          auth: true
          starttls:
            enable: true
    username: aprimonsjavaproject@gmail.com
    password: izxo fbon csaj rsov
  messages:
    basename: messages/messages
    encoding: utf-8
logging:
  level:
    org.springframework.security: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true